### ISSUE TITLE
how to run this code in Jupiter Notebook ? how to specify ap.add_argument? 

### ISSUE THREAD

**Issue by gpandi007** [Furkan-Gulsen/OpenCV-Projects#1]
how to run this code in Jupiter Notebook ?

am getting the error in 
ap.add_argument('-i', '--images', required=True,)

error is 

usage: ipykernel_launcher.py [-h] -i IMAGES [-t THRESHOLD]
ipykernel_launcher.py: error: the following arguments are required: -i/--images

how to specify the ap.add_argument? do i need to create separate folder ? please read the error

**Comment by Furkan-Gulsen** [comment]
I'm sorry for the late reply. If you are running these codes on the Jupyter notebook, it is better not to use argparse. Argparse is generally used to write more functional code on the command screen. But if you still want to write in jupyter notebook, you can solve your problem like the solution in the link below.
[https://stackoverflow.com/questions/30656777/how-to-call-module-written-with-argparse-in-ipython-notebook](https://stackoverflow.com/questions/30656777/how-to-call-module-written-with-argparse-in-ipython-notebook)

**Comment by Furkan-Gulsen** [comment]
> how to run this code in Jupiter Notebook ?
> 
> am getting the error in
> ap.add_argument('-i', '--images', required=True,)
> 
> error is
> 
> usage: ipykernel_launcher.py [-h] -i IMAGES [-t THRESHOLD]
> ipykernel_launcher.py: error: the following arguments are required: -i/--images
> 
> how to specify the ap.add_argument? do i need to create separate folder ? please read the error
