### ISSUE TITLE
Missing attribution and citing (possible plagarism)

### ISSUE THREAD

**Issue by jrosebr1** [Furkan-Gulsen/OpenCV-Projects#2]
Hey there @Furkan-Gulsen -- Adrian here from PyImageSearch.com. One of my readers pointed that that this GitHub repo and [your associated Medium article](https://medium.com/analytics-vidhya/how-to-perform-blur-detection-using-opencv-in-python-11a535559334) use code and content from my original tutorial on blur detection:

https://www.pyimagesearch.com/2015/09/07/blur-detection-with-opencv/

Per my FAQ, you must reference and cite my tutorials if you are using code/content from them:

https://www.pyimagesearch.com/faqs/single-faq/how-do-i-reference-or-cite-one-of-your-blog-posts-books-or-courses

I ask that you update your Medium article and GitHub repo to properly cite your sources.

Thanks!

**Comment by Furkan-Gulsen** [comment]
@Adrian Rosebrock Sorry, Adrian. I'm fixing now.
